objects:
  "ミャクミャクの椅子":
    frame_id: map
    x: -0.4616
    y: -0.1336
    yaw: 1.57
  "抹茶の箱":
    frame_id: map
    x: 0.5555
    y: -0.6994
    yaw: 3.14
  "3Dプリンター":
    frame_id: map
    x: 0.4557
    y: 0.4359
    yaw: -1.57
