objects:
  "ミャクミャクの椅子":
    frame_id: map
    x: -1.0763
    y: 0.1095
    yaw: 1.57
  "抹茶の箱":
    frame_id: map
    x: 0.6696
    y: -0.5724
    yaw: 3.14
  "3Dプリンター":
    frame_id: map
    x: 0.5882
    y: 0.9352
    yaw: -1.57
